export interface recipesType {
  id: string;
  name: string;
  ingredients: string[];
  instructions: string[];
  cookTime: string;
}

export const recipes: recipesType[] = [
  {
    id: "1",
    name: "Fried eggs, Bread and Tea",
    ingredients: [
      "4 Fresh eggs",
      "50 ml Vegetable oil",
      "1/2 cup chopped tomatoes",
      "Small chopped onions",
      "1 sliced pepper (scotch bonnet)",
      "Salt to taste",
      "Seasoning cube (a pinch)",
    ],
    instructions: [
      "Heat your frying pan for a minute then add 50 ml of vegetable oil, allow to heat for 30 seconds before adding the sliced onions, then tomato/pepper as well.",
      "Fry for 5 minutes before spraying a pinch of salt (to taste), then about a half of seasoning cube (I prefer less)",
      "Stir, and then make sure they spread evenly it on the frying pan and boiling in very little oil. Then pour in the (already broken and mixed eggs) to cover the onions, tomato combination.",
      "Allow frying for a minute before flipping.",
      "Allow another 1 minute.",
      "Flip. Flip again.",
    ],
    cookTime: "8 minutes",
  },
  {
    id: "2",
    name: "Ewa Agoyin and Bread",
    ingredients: [
      "1 cup of dried crushed chilies/peppers",
      "1 white onion",
      "Large red onion (one)",
      "1 Seasoning cube",
      "Salt to taste",
      "2 cups palm oil",
      "3 cups of beans/black-eyed peas",
      "Any bread of your choice",
    ],
    instructions: [
      "Slice half of the red onion and combine the remaining half with the white onions, pepper, a cup of water and blend.",
      "Set your cooking pot on heat, add the two cups of palm oil and allow heating, but don’t let it bleach. About 3 minutes should do it",
      "Throughout the cooking process, you don’t let it bleach when making ewa agoyin, the red color is just what set’s it apart from the regular tomato stew.",
      "Once the oil is heated you can add the sliced red onions",
      "Fry the onion for about 3 minutes before adding the ground pepper/chilli, onions and water combination",
      "Now fry for the next 15-25 minutes on low heat",
      "You will notice the sauce drying and turning dark, check to ensure the pepper looks like small pebbles or grainy sand",
      "Stir the sauce for 2 minutes",
      "Add a cube of seasoning and salt to taste",
      "It should be dried but not burned.",
      "Add the beans to boiling water and allow it to simmer for about 5 minutes, turn off the heat, wash and set aside.",
      "Boil 5 cups of water and start cooking the beans in it. You can add more water in-between, we want it really soft. Add a teaspoon of salt.",
      "Cook until the beans are really soft, then serve with the pepper sauce and any bread of your choice.",
    ],
    cookTime: "1 hour",
  },
  {
    id: "3",
    name: "Fried Yam and Tomato Sauce",
    ingredients: [
      "Yam",
      "10 balls of tomatoes",
      "Fresh pepper to taste",
      "1 cup of sliced onions",
      "1 seasoning cube",
      "Vegetable / Olive oil",
    ],
    instructions: [
      "Peel off the back of the yam, slice to any size of your choice and deep-fry. It is necessary to add a little bit of salt before frying.",
      "Fry for a few minutes, always turning up and down to avoid burning.",
      "You can use a frying pan or a cooking pot to make the sauce",
      "Set the pot on fire, add about 20cl of olive / vegetable oil, allow heating, then pour in the chopped or blended tomatoes/pepper.",
      "Fry for about ten minutes and add the onions. Fry (while stirring occasionally for another ten to fifteen minutes to lose the lousy sour taste)",
      "Add a seasoning cube and salt.",
      "Add a fluted pumpkin (optional)",
      "Taste for salt and pepper",
      "Serve with the Fried yam.",
    ],
    cookTime: "45 minutes",
  },
  {
    id: "4",
    name: "Bread, Akara and Pap",
    ingredients: [
      "3 cups black-eyed or brown beans",
      "1 small red onion",
      "Hot spicy pepper(habanero, scotch bonnet or fresh cayenne pepper)",
      "Salt to taste",
      "Vegetable oil",
      "Pap (brown, white or yellow)",
      "Water",
      "Evaporated Milk and sugar",
      "Any bread of your choice",
    ],
    instructions: [
      "Soak the beans for 20 - 30 minutes to make it easier to peel",
      "Wash and peel to reveal the white beans",
      "When done, soak the beans in water for at least one hour to soften it. This is so your blender will grind it into the smoothest paste",
      "Chop the onions and pepper into tiny pieces.",
      "After at least one hour, remove the beans seeds from the water and put in a sieve.",
      "Grind them bit by bit in a blender, using very little water.",
      "Set the blended beans in a bowl, add salt and the chopped onions and hot and spicy pepper, mix very well and taste to ensure that it doesn't taste raw",
      "Set some oil to heat up. Akara should be deep fried so make sure the oil is at least 2 inches deep.",
      "When the oil is hot, scoop the beans paste into the oil.",
      "A well whisked beans paste should float on the oil. If it sinks, it means the beans paste was not well whisked, the oil is not hot enough, the paste is too watery, or all of the above.",
      "Fry the underside till you notice it browning and the raw top has increased in size showing that the inside has cooked (somehow). Then flip to fry the top side.",
      "It is done when golden all over.",
      "Put some lumps of pap into a sizeable bowl. Pap rises during preparation so you should use a bowl big enough to contain the meal in its risen state.",
      "Use a tablespoon to crush the lumps of ogi into very small pieces.",
      "Add cool water in small quantities and mix till you have a medium consistency with no lumps. Your aim should be to mix the akamu as thick as possible.",
      "Put a kettle of water to boil. Make sure the water will be enough. It is better to boil too much water than not have enough water when making pap.",
      "Just before the water boils, stir the mix very well because some of the pap may have settled at the bottom of the bowl. If not stirred well, this is the major cause of lumps when you start making it.",
      "Once the water boils, pour it slowly but steadily in a circular motion into the bowl of akamu and stir at the same time. Pouring the hot water slowly and stirring at the same is very important because this prevents lumps.",
      "The moment you see the mixture setting, stop stirring and reduce the flow of water you are pouring till the akamu has completely set.",
      "Set the kettle aside and stir the pap very well. If it is too thick for you, you can add more hot water. But be careful else it will become watery.",
      "Add the evaporated milk and sugar to taste and stir everything the way you like it, serve with akara and and any bread of your choice.",
    ],
    cookTime: "2 hours",
  },
  {
    id: "5",
    name: "Waakye",
    ingredients: [
      "1 pound boneless goat shoulder",
      "3 teaspoons kosher salt",
      "1 teaspoon Guinea pepper (also known as grains of Selim)",
      "1 teaspoon grains of paradise (also known as alligator pepper seed)",
      "3 cups chopped red onion",
      "1 tablespoon grated fresh ginger",
      "2 small red bell peppers, seeded and coarsely chopped",
      "1 small fresh Scotch bonnet",
      "½ cup, plus 2 tablespoons of peanut oil",
      "2 medium garlic cloves, finely chopped",
      "1 teaspoon light brown sugar",
      "1 teaspoon paprika",
      "1 teaspoon corn flour",
      "½ teaspoon ground turmeric",
      "¾ cup water",
      "1 teaspoon cayenne pepper",
      "¼ teaspoon plus 1/8 teaspoon ground allspice and black pepper",
      "⅛ teaspoon ground cloves",
      "1 pinch of ground nutmeg, cinnamon and ginger",
      "1 tablespoon dried ground crayfish or prawn/shrimp powder",
      "½ cup canned tomato sauce (from 8-oz. can)",
      "chicken stock",
      "1 cup uncooked long-grain white rice, such as basmati",
      "1 tablespoon coconut oil",
      "1 medium yellow onion, finely chopped",
      "1/2 teaspoon baking soda",
      "2 fresh Anaheim chiles or Thai chiles",
      "1 ¼ cup drained and rinsed canned black-eyed peas",
    ],
    instructions: [
      "Toss goat with 1 teaspoon of the salt in a medium bowl for 25 minutes.",
      "Meanwhile, grind Guinea pepper pods in a mortar and pestle; remove grains and discard any pods.",
      "Toast Guinea pepper and grains of paradise in a small skillet over medium, stirring constantly for 1 minute.",
      "With a mortar and pestle, grind Guinea pepper mixture to a coarse powder.",
      "Add 1 cup of the onion and 1 teaspoon of the fresh ginger; grind and smash into smooth juicy paste. Set spice paste aside.",
      "Process red bell peppers, plum tomatoes, Scotch bonnet chile, 1 cup of the onions, 1 teaspoon of the fresh ginger, and 1 teaspoon of salt in a blender until smooth then set aside.",
      "Heat remaining 1/2 cup oil in same pan over medium heat, add cayenne pepper and remaining 1 cup onion and 1 teaspoon fresh ginger.",
      "Cook, stirring occasionally, until onions are brown around the edges for about 6 minutes.",
      "Add allspice, black pepper, cloves, nutmeg, cinnamon, and ground ginger, and stir to coat onion mixture in spice mixture.",
      "Stir in ground guinea pepper spice paste, return seared goat along with drippings to a pan and cook, stirring constantly for 3 - 4 minutes.",
      "Stir crayfish powder into goat mixture, add processed bell pepper mixture, tomato sauce, and chicken stock. ",
      "Bring to a simmer over medium-high. Reduce heat to low, and simmer, stirring and scraping bottom of pan occasionally, until goat is tender, sauce thickens, and stew darkens in color for about 45 minutes to 1 hour.",
      "Place rice in a medium bowl, add water to cover, and swirl rice with your hand.",
      "Drain through a fine mesh strainer; return rice to bowl. Repeat process until water is clear when swirled with rice.",
      "Heat a large, heavy saucepan over medium, add coconut oil and yellow onion and cook stirring occasionally until onions are lightly browned around the edges for about 6 minutes.",
      "While onions cooks, swiftly rinse dried millet leaves under water because the color will start to run as soon as they get wet; cut into 3-inch pieces.",
      "Add sliced chiles, black-eyed peas, millet leaves or baking soda, salt, and drained rice to onion mixture in pan, and stir to coat each grain of rice in oil.",
      "Stir in stock and bring to a boil over high, reduce heat to low, cover and simmer for 12 minutes.",
      "Turn off heat and let stand, covered, until water is absorbed and rice is very tender for about 8 -12 minutes.",
      "Serve the stew ladled over the rice. Top with eggs, chives, sesame seeds, avocado slices, Shito hot pepper sauce, chiles, and cilantro, if desired.",
    ],
    cookTime: "2 hours 20 minutes",
  },
  {
    id: "6",
    name: "Tom Brown",
    ingredients: [
      "Guinea corn",
      "Millet",
      "Soybeans",
      "Yellow corn",
      "Dates",
      "Groundnuts",
      "Ginger powder",
      "Dried sweet potato powder",
    ],
    instructions: [
      "On a low heat, roast the yellow corn until its turned golden brown.",
      "Add groundnut, guinea corn, millet and soya beans.",
      "After roasting, ground them into a powder form.",
      "Tom brown is ready, you can pour it inside a dry container and preserve it, it can be a mix for consumption with pap, custard, tea",
      "place a small pot on fire, pour small water into it then make a thick mix of tom brown with water and pour it into the pot.",
      "using a wooden spatula, stir until there’s no lump in the mixture and it starts to thicken.",
      "Add a little pinch of salt and nutmeg (optional).",
      "For a spicy taste, add some cinnamon powder to the mixture and stir.",
      "Add more water if the paste is too thick for you.",
      "Add honey or sugar to taste and stir consistently.",
      "Reduce heat and allow the mixture to boil for about 5 minutes.",
      "Adjust sugar. Remove from heat and serve tom brown hot.",
      "You can serve this yummy cereal with milk, sweeteners and some slice of bread.",
    ],
    cookTime: "1 hour",
  },
  {
    id: "7",
    name: "Hausa Koko and Kose",
    ingredients: [
      "2 cups of whole pearl millet (or 1 cup of millet and 1 cup of sorghum)",
      "5 grains of selim",
      "1/2 teaspoon of black peppercorn",
      "5 calabash nutmegs",
      "2 large thumbs of ginger",
      "1/2 teaspoon grains of paradise",
      "1/2 teaspoon of whole cloves",
      "1.5 cups of dried black eye peas",
      "1/2 red onion",
      "1/4 teaspoon of salt",
      "Water",
      "Vegetable oil",
      "",
    ],
    instructions: [
      "Clean the grains and soak overnight with a lot of water.",
      "The next day, wash the grains very well and blend with spices and blend with about 2-3 cups of water.",
      "Once you have a smooth mixture, strain the mix through a cheesecloth. You can also use a nut milk back but I find that the nut milk back is too fine of a sieve.",
      "Blend the chaff (the left over) with more water (another 2 cups of water) and repeat the straining process.",
      "Cover the strained liquid with a cloth and let it ferment overnight. You should have close to a litre of the mixture",
      "Also, soak the beans in water.",
      "The next day, heat your oil for frying and blend the beans with salt and just enough water to get the beans to blend. Start off with as little water as possible and add enough to get a thick batter.",
      "Use a spoon to scoop a little bit of the batter and drop it into the hot oil. Repeat till you have used all the batter.",
      "Once the kose is ready, move on to cooking the porrigde",
      "By now there should be some bubble on top. The water should have separated at the top, Carefully pour the liquid into a pot without disturbing the thick mixture at the bottom and bring to a boil.",
      "As the liquid is a boiling, mix the mixture at the bottom into a thick paste.",
      "Once the water comes to a boil, add the thick paste. turn the burner off and continue to whisk everything. The porridge will get thicker. Add more water if you feel that it is getting too thick.",
      "Serve porridge with sugar and roasted peanuts with a few pieces of kose.",
    ],
    cookTime: "2 days",
  },
  {
    id: "8",
    name: "Tatale (plantain pancakes)",
    ingredients: [
      "Over ripe plantains",
      "Scallions",
      "Red bird’s eye chillies",
      "Self rising flour",
      "salt",
      "Egg",
      "Red palm oil",
      "Vegetable oil",
    ],
    instructions: [
      "Peel the plantains, blend it into a smooth paste",
      "Add chopped scallions, red bird's eye chillies, self rising flour, egg and salt.",
      "With wet hands, form into pancake shape.",
      "Heat some vegetable oil in a pan.",
      "Shallow fry the pancakes until golden brown on both sides.",
      "Drain on paper towels and serve hot with a beverage of your choice",
    ],
    cookTime: "30 minutes",
  },
  {
    id: "9",
    name: "Akla (Beans Fritters)",
    ingredients: [
      "3 cups black-eyed beans",
      "1 onion, finely chopped",
      "1 teaspoon salt",
      "1 scotch bonnet ( or other hot pepper)",
      "3 cloves of garlic",
      "Spring onions (optional)",
      "2 teaspoons fresh ginger root, peeled and minced",
      "Vegetable oil for frying",
    ],
    instructions: [
      "Rinse and soak the black-eyed beans in water for at least a few hours or overnight.",
      "Once they have been soaked properly, rub them together between your hands to remove the skins i.e. the blacks bits of the beans.",
      "Rinse to wash away the skins and any other debris.",
      "Repeat this (rubbing and washing) several times until the black bits are largely washed away.",
      "Drain the beans.",
      "Blend the black-eyed beans, ginger, garlic, peppers and onions into a paste, adding just about enough water. A good test is to see if the batter clings to a spoon.",
      "Add salt to taste.",
      "Heat vegetable oil in a deep pan.",
      "Make the Akla by scooping up a spoon full of the batter and dropping it into the hot oil.",
      "Serve with Hausa koko (porridge) as a snack or as a side dish.",
      "Note: A whisked egg, cornmeal or crushed breadcrumbs can be added to the blended akla to protect it from disintegrating when it is dropped in hot oil.",
    ],
    cookTime: "2 hours 30 minutes",
  },
  {
    id: "10",
    name: "Oblayo",
    ingredients: ["Corn (roughly ground)", "Water", "Sugar", "Milk"],
    instructions: [
      "Pour some corn into a bowl and add water to it.",
      "Stir and wait for the corn to settle, the chaff will surface, then pour away the chaff from it.",
      "Put water on fire in a saucepan, pour in your corn and stir.",
      "Stir from time to time and leave it to cook for a while.",
      "Cook until you can squash the corn.",
      "If you want it lighter, you can add some more water and stir and let it cook for a little more time.",
      "Pour into a bowl when it’s ready and add your sugar and milk as you want it.",
    ],
    cookTime: "10 minutes",
  },
  {
    id: "11",
    name: "Rice Water",
    ingredients: [
      "1 cup rice",
      "Water",
      "1 teaspoon salt",
      "½ teaspoon nutmeg",
      "honey/ sugar any sweetener of choice",
      "powdered or evaporated milk to serve",
      "Dash of nutmeg for garnish (optional)",
    ],
    instructions: [
      "Wash rice, pour in a large saucepan with 5 cups of water and put on a high heat.",
      "Boil for about 20 minutes till the rice has soaked the water and soft.",
      "Add the salt and one cup of water if needed.",
      "Using a ladle, beat the rice against the saucepan to form a smooth- pudding like consistency.",
      "Add the nutmeg and sweetener of choice let it simmer for about five minutes.",
      "Serve with milk of choice and sprinkle with tiny dash of nutmeg for garnish.",
    ],
    cookTime: "32 minutes",
  },
  {
    id: "12",
    name: "Salatu Niebe (black-eyed beans salad)",
    ingredients: [
      "1/2 pound black-eyed beans, soaked in water preferably overnight",
      "Water",
      "Salt and freshly ground black pepper",
      "1 tomato or 4 cherry tomatoes diced",
      "1 cucumber diced",
      "1 red bell pepper and 1 orange bell pepper diced",
      "A bunch of scallions chopped",
      "1/2 a bunch Italian parsley finely chopped",
      "Juice of 2 limes",
      "1 teaspoon of cumin",
      "1 habanero pepper finely chopped",
      "½ a cup of extra virgin olive oil",
    ],
    instructions: [
      "Boil the black-eyed beans in a pot with the water until tender.",
      "The beans are tender when one or two easily turns to mash when pressed between your fingers.",
      "Add all the other ingredients such as tomatoes, cucumber, bell pepper, scallions, parsley, lime juice, salt and habenero to the boiled and drained black-eyed beans in a bowl.",
      "Pour in the extra virgin oil and whisk.",
      "Allow the mixture to sit for an hour before serving.",
    ],
    cookTime: "45 minutes",
  },
  {
    id: "13",
    name: "Jamaican Ackee and Saltfish",
    ingredients: [
      "Salted codfish",
      "Bacon",
      "Vegetable oil",
      "Onion",
      "Garlic",
      "Thyme",
      "Scallions or green onions",
      "Tomato",
      "Scotch Bonnet",
      "White and bell pepper",
      "Paprika",
      "Ackee",
    ],
    instructions: [
      "Soak salt codfish in water overnight in a covered container.",
      "Sauté the Fresh Ingredients.",
      "In a large skillet over medium heat, sauté bacon until brown and crisp, this may take about 3-5 minutes. ",
      "Remove your bacon from the skillet and transfer it to a plate.",
      "Remove most of the bacon drippings from your skillet but leave about 1-2 tablespoons in the pan.",
      "Add about 2 Tablespoons of vegetable oil to the pan. (Or you could use the bacon drippings)",
      "Now add the tomatoes and continue cooking for about 3 minutes.",
      "Add the Scotch bonnet pepper and freshly ground pepper and mix until ingredients have been thoroughly combined.",
      "Cook another 5 more minutes or so, adding water if the pan gets too dry.",
      "Throw in the saltfish and cook for 2-3 minutes.",
      "Add ackee and cook for another 3 minutes or so.",
      "Adjust the seasoning to taste.",
      "Remove from the heat, serve, and enjoy your Jamaican ackee and saltfish!",
    ],
    cookTime: "45 minutes",
  },
  {
    id: "14",
    name: "Banana Fritters",
    ingredients: [
      "3 ripe bananas",
      "1 teaspoon vanilla Extract",
      "½ teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "3 tablespoon brown sugar",
      "Pinch of salt",
      "1 cup all purpose flour",
      "Vegetable oil",
    ],
    instructions: [
      "Peel bananas and smash them together with a fork until they are mashed and a little watery.",
      "Then add your vanilla extract, cinnamon, nutmeg, brown sugar, and salt to the mashed bananas.",
      "Next, add the all purpose flour, you can use a sifter to add it. ",
      "Stir with a spoon until your mixture is fully combined. Your batter should not be too thick or thin but should flow easily off a spoon.",
      "Pour about ¼ cup oil in a 10 inch skillet and heat it over medium-high heat.",
      "Once the oil is hot, pour the fritters in pan by the spoonful.",
      "Once bubbles appear in the top of the fritter and the bottom is golden brown, flip the fritters and cook until the other side is brown as well.",
      "Remove fritters from skillet and drain on paper towel",
      "Serve with any beverage or juice of your choice",
    ],
    cookTime: "20 minutes",
  },
  {
    id: "15",
    name: "Jamaican Corn Meal Porridge",
    ingredients: [
      "2 cups water",
      "2-3 cups coconut milk",
      "½ cinnamon stick",
      "½ teaspoon salt and nutmeg",
      "1 cup yellow cornmeal",
      "1 teaspoon vanilla extract",
      "Sweeteners (condensed milk, coconut sugar and brown sugar)",
      "½ cup sweetened condensed milk",
    ],
    instructions: [
      "Add about 2 cups water and 2 cups coconut milk to a heavy large saucepan, throw in ½ stick cinnamon stick and bring to a boil",
      "Gradually whisk in the cornmeal, until you have add the whole thing in the pot, a little bit at a time and keep stirring with a wooden spoon to prevent any lumps.",
      "Reduce the heat to low and cook until the mixture thickens for about 15 minutes.",
      "Add flavoring vanilla extract, nutmeg and sweetened condensed milk.",
      "Adjust consistency with coconut and/or water if desired.",
      "Turn off the heat. Serve piping hot with extra nutmeg and sweeteners",
    ],
    cookTime: "25 minutes",
  },
  {
    id: "16",
    name: "Jollof Rice",
    ingredients: [
      "Rice",
      "Tomatoes",
      "Tomato paste",
      "Onions",
      "Green and red bell peppers",
      "Garlic and ginger",
      "Chicken broth",
      "Seasoning cubes",
      "Thyme, bay leaves and curry powder",
      "Vegetable oil",
    ],
    instructions: [
      "Wash the rice in a bowl until the water runs clear.",
      "Peel and chop the onions, green and red bell peppers, garlic, and ginger.",
      "Blend the tomatoes, tomato paste, and spices to form a sauce.",
      "Heat oil in a pot and fry the chopped onions, peppers, garlic, and ginger until they are fragrant.",
      "Add the blended sauce to the pot and stir until heated through.",
      "Add the chicken broth to the pot and bring to a boil.",
      "Stir in the rice, making sure that it is evenly distributed.",
      "Reduce heat to low and let the rice cook for about 15-20 minutes or until the liquid has been fully absorbed.",
      "Stir occasionally to prevent the rice from sticking to the bottom of the pot.",
      "Serve hot with fried plantains and chicken.",
    ],
    cookTime: "1 hour",
  },
  {
    id: "17",
    name: "Plantain Porridge",
    ingredients: [
      "2 medium sized plantains (ripe, semi ripe or unripe)",
      "1 smoked fish or fresh fish(preferably mackerel)",
      "About 400gram or 1 bunch Ugwu leaves (use Spinach, Kale or Green amaranth as substitute)",
      "1 large Onion bulb",
      "1 tablespoonful Ground Crayfish",
      "1 cooking spoonful Palm oil",
      "1 Large seasoning cube or 1 teaspoonful seasoning powder",
      "Salt to taste",
      "Chili or Scotch bonnet (atarodo) Pepper to taste",
    ],
    instructions: [
      "Peel and chop the onions.",
      "Chop or grind the pepper.",
      "Wash, peel and cut the plantains into small sizes.",
      "Then wash the vegetables and slice into thin strips and set all aside for later use.",
      "Now, wash and clean the fish.",
      "If using smoked fish, clean with hot water and set aside, if using fresh fish remove the gut, cut and set aside.",
      "Place the plantains into a pot, add enough water to slightly cover the plantains.",
      "Then add the chopped onions, the fish, ground crayfish, pepper and seasoning cube or powder.",
      "Leave to cook until it starts to boil.",
      "Add the palm oil and salt to taste.",
      "Leave to cook until the plantains are tender.",
      "Finally, add the sliced vegetables, and simmer covered for 3 minutes.",
      "Stir  thoroughly, serve and enjoy.",
    ],
    cookTime: "35 minutes",
  },
  {
    id: "18",
    name: "Maafe Soup",
    ingredients: [
      "¼ cup oil or more",
      "1 - 2 pounds beef or chicken",
      "1 teaspoon smoked paprika",
      "½ teaspoon white pepper",
      "2 fresh tomatoes chopped",
      "1 medium onion chopped",
      "3 - 4 garlic cloves",
      "2 - 3 tablespoons parsley",
      "½ cup ground peanuts or Peanut butter paste",
      "3 - 4 cups broth chicken or beef",
      "1 or more pound vegetable (potatoes & carrots)",
      "1 whole scotch bonnet or habanera pepper or ½ teaspoons cayenne pepper (optional)",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large saucepan, season meat with salt, and onions and boil until tender.",
      "Depending on the choice of meat, you should have at least 3-4 cups of stock.",
      "Remove the meat and reserve stock (broth).",
      "In a large pot, heat oil over low heat, then add the beef/chicken and sauté, stirring frequently any browned bits off the bottom of the pot.",
      "Remove and set aside.",
      "Blend tomatoes, 1/2 onion, garlic, and parsley.",
      "Add half of the onions to the pan , sauce for about a minute and pour the mixture in the saucepan.",
      "Add paprika, white pepper and sauté for about 7 - 10 minutes. Stirring frequently to prevent burns, add stock as needed.",
      "Then add potatoes, Carrots, peanut butter paste, scotch bonnet pepper and about 3 cups broth.",
      "Continue cooking until potatoes tender- about 10 or more depending on vegetables.",
      "Throw in the browned beef, adjust the soup thickness with water if necessary.",
      "If not, return your soup to the heat and let simmer to desired thickness",
      "Drip a little soup from your stirring spoon, if you are satisfied with the thickness of your soup, serve it with rice or cous cous.",
    ],
    cookTime: "55 minutes",
  },
  {
    id: "19",
    name: "Moi moi and Pap or Garri",
    ingredients: [
      "700g Black eyed or brown beans",
      "1 Tatashe(red bell pepper)",
      "1 scotch bonnet pepper(atarodo/fresh pepper)",
      "2 cooking spoonful palm oil",
      "1 tablespoonful concentrated tomato puree (for extra color, but optional)",
      "4 Tablespoonful ground Crayfish",
      "2 large Onions bulbs",
      "Eggs OR boiled minced meat OR Bone Marrow  OR Corned beef OR deboned smoked fish OR deboned boiled fish",
      "3 bouillon/stock cubes for Seasoning",
      "Water",
      "Salt",
    ],
    instructions: [
      "First soak the beans for about 1 hour (or overnight) and wash it, by scrubbing off the bean coat/skin.",
      "Make sure to remove all the bean coat until you are left with white coat-less beans.",
      "Choose what extra garnishes you want to add to the Moimoi,",
      "If it’s eggs, boil the eggs, remove the shells and slice into small pieces, then set aside.",
      "If it’s fresh fish, boil the fish, remove bones and cut into small pieces.",
      "If you prefer corned beef or sardines, then take it out of the can, and set aside.",
      "Grease/Oil the containers you’ll be using.",
      "If you prefer Banana Leaves/ Uma Leaves(Thaumatococcus Daniellii), then wash thoroughly and leave to dry out in a colander/sieve.",
      "Wash the peppers and slice the onions.",
      "Strain the beans, pour it into your blender(do this in batches).",
      "Add the peppers(you can also add thick tomato paste, to give it more color).",
      "Add the onions, crayfish and stock cubes.",
      "Add a little water to help the blender work better. Grind the beans until you get a very smooth consistency, without granules or beans lumps.",
      "*If you’re using bean flour, mix the flour in a little water to form a thick paste, then pour the paste into a blender,add the peppers,onions, crayfish and stock cubes and blend until smooth.*",
      "Pour the blended beans into a wide bowl;Stir and slowly add some water and continue stirring until you get a lighter consistency, but not too watery.",
      "Now, add the palm oil, taste for salt and if need be, add a little salt(remember you already added stock cubes, so go easy on the salt).",
      "Mix thoroughly and then take out your greased moi moi containers or moi moi leaves.",
      "Pour the mixture into each of the containers and add your egg or any other garnishes you prefer.",
      "Seal or cover the containers and set aside.",
      "Now, line the base of your pot with foil paper or the same moi moi leaves, lay the sticks before the leaves.",
      "Pour in some water and set to boil. When the water is boiling, place the sealed Moi moi into the pot of boiling water and leave to steam.",
      "As the Moi moi starts to cook. Add a little quantity of water from time to time,so that it doesn’t begin to burn underneath.",
      "*But be careful not to add to much water as it might get into the Moi moi containers and ruin the food by making it watery.*",
      "After about 45 minutes, put a knife through the Moi Moi; if the knife comes out clean, then the moi moi is ready.",
      "*Note that the cooking time for Moi Moi depends on the type of container you are using and also on the quantity of moi moi you are cooking*",
      "If you are in doubt about whether the Moi moi is well cooked or not; it is advisable to leave it to cook for about 1 hour 30 minutes(adding some water occasionally).",
      "The moi moi tends to cook faster with the foil, nylons and leaves, but takes longer with the plastic bowl.",
      "Now , take out the Moi moi from the pot and leave to cool a bit before unwrapping or turning it onto a plate. Pair with pap or chilled garri and enjoy!",
      "*Tip: A steamer is great for cooking Moi moi.*",
    ],
    cookTime: "3 hours",
  },
  {
    id: "20",
    name: "Plantain and Scrambled Egg",
    ingredients: [
      "3 eggs",
      "1 tomato chopped",
      "1 small onion chopped",
      "1/4 red bell pepper",
      "1 green chilli",
      "Salt",
      "1 tablespoon margarine",
      "5 tablespoon oil",
    ],
    instructions: [
      "In a bowl, crack the eggs and add the onion, tomato, peppers, green chilli, and season with salt, whisk together",
      "In a pan, add margarine and once melted pour in the egg mixture.",
      "Let it cook for 1 minute and then scramble it using a spatula.",
      "Cook for 1 - 2 minutes and set aside.",
      "In another pan heat oil and place the plantain slices cook for 2- 3 minutes on each sides until golden brown.",
      "Serve fried plantains with scrambled eggs.",
    ],
    cookTime: "50 minutes",
  },
  {
    id: "21",
    name: "Mushroom And Spinach Omelette",
    ingredients: [
      "1 tablespoon oil",
      "1 teaspoon garlic minced",
      "Quarter cup mushroom thinly sliced",
      "Salt",
      "Freshly ground black pepper",
      "Quarter cup spinach chopped",
      "2 eggs",
      "1 teaspoon margarine spread",
    ],
    instructions: [
      "Heat oil in a pan and sauté the garlic in it.",
      "Add the mushrooms, season with salt and pepper and cook for 2 minutes.",
      "Add the spinach, stir and set aside to cool completely.",
      "Once cooled, crack 2 eggs in a bowl and mix in the mushroom and spinach mixture.",
      "Heat margarine in a pan and add the egg mixture.",
      "Spread it out and cook for 1 ½ minutes on one side and then flip and cook for another 30 seconds.",
      "Serve with some toast and tea.",
    ],
    cookTime: "20 minutes",
  },
  {
    id: "22",
    name: "French Toast",
    ingredients: [
      "1 egg",
      "2 slices bread",
      "1/2 teaspoon vanilla extract",
      "Quarter teaspoon cinnamon powder",
      "3 tablespoon milk",
      "Salt",
      "1 tablespoon peanut butter",
    ],
    instructions: [
      "In a shallow dish, whisk together egg, vanilla, cinnamon, milk and salt.",
      "Dip the bread in the egg mixture and turn to coat both sides.",
      "Heat 1/2 tsp oil in a pan and place the bread on it.",
      "Cook for 1 minute on each side or until browned.",
      "Serve with a drizzle of peanut butter and sliced strawberries.",
    ],
    cookTime: "6 minutes",
  },
  {
    id: "23",
    name: "Chicken Sandwich",
    ingredients: [
      "2 tablespoons Oil",
      "Chicken breasts",
      "Salt",
      "Paprika Powder",
      "Mixed herbs",
      "Margarine",
      "Bread slices",
      "Lettuce",
      "Grated cheddar cheese",
    ],
    instructions: [
      "Add oil to a pan and when hot put on the 2 chicken breasts and season with salt, paprika powder, and mixed herbs.",
      "Cook the chicken breasts for 6-7 minutes on each side and shred the chicken.",
      "Spread margarine on toasted bread.",
      "Top with lettuce, shredded chicken, grated cheese and serve",
    ],
    cookTime: "20 minutes",
  },
  {
    id: "24",
    name: "Peanut Butter & Chocolate Chip Pancakes",
    ingredients: [
      "1 cup all-purpose flour",
      "Quarter cup sugar",
      "1 half baking powder",
      "Quarter teaspoon salt",
      "Half cup of peanut butter",
      "1 teaspoon vanilla essence",
      "1 egg beaten",
      "1 cup milk",
      "Half cup chocolate chips",
      "Banana",
    ],
    instructions: [
      "In a large bowl, mix together flour, sugar, baking powder and salt.",
      "Add the peanut butter in another bowl and microwave for 30-40 seconds.",
      "Once the peanut butter is runny, whisk into it the vanilla, egg and milk.",
      "Pour the dry ingredients into the wet ingredients and mix until combined.",
      "Fold in the chocolate chips.",
      "Scoop up 1/2 cup of the batter and pour onto a greased griddle/pan over a medium flame.",
      "Cook for 45 seconds on one side and flip. Cook for another 15 seconds and then take it off the heat.",
      "Top with sliced bananas and a drizzle of peanut butter before serving.",
    ],
    cookTime: "13 minutes",
  },
  {
    id: "25",
    name: "Carrot Pancake",
    ingredients: [
      "1/4 teaspoon margarine",
      "1 1/2 all-purpose flour",
      "2 tablespoons finely chopped walnuts",
      "1 teaspoon ground cinnamon",
      "1/4 teaspoon salt",
      "1 whole egg",
      "1/2 cup brown sugar",
      "1 cup milk",
      "1 1/2 grated carrots",
      "1 teaspoon vanilla extract",
    ],
    instructions: [
      "In a large bowl, combine all dry ingredients except the grated carrots and brown sugar. Set aside.",
      "Using a cheesecloth pat the grated carrots until its juices are absorbed then set aside.",
      "In another bowl combine all the wet ingredients together with the brown sugar and the grated carrots.",
      "Add the dry ingredients to the wet ingredients and mix just until the mixture is moistened.",
      "Do not overmix(The mixture is meant to be lumpy).",
      "Heat a frying pan with medium heat and add the margarine.",
      "Once melted pour batter by 1/4 cupfuls.",
      "Turn when bubbles form on top of the pancake",
      "Cook until the second side is golden brown.",
      "Transfer to a plate and serve.",
    ],
    cookTime: "15 minutes",
  },
  {
    id: "26",
    name: "Peanut Sauce Pasta",
    ingredients: [
      "200 grams spaghetti pasta",
      "3 tablespoons peanut butter",
      "2 tablespoons soy sauce",
      "1 tablespoon vinegar",
      "1 tablespoon honey",
      "1 tablespoon lemon juice",
      "1/2 teaspoon chilli flakes",
      "1/4 teaspoon pepper",
      "1/4 teaspoon salt",
      "3 garlic cloves minced",
      "1 teaspoon ginger minced",
      "1 cup mushrooms",
      "1 cup broccoli florets",
      "1/2 cup carrots",
      "Water",
      "Sesame seed to garnish",
    ],
    instructions: [
      "Cook spaghetti pats according to package instructions.",
      "In a bowl mix peanut butter, soy sauce, vinegar, lemon juice, hone, chilli flake, pepper and salt.",
      "In a pan add oil, add garlic and ginger and cook for 1 min.",
      "Add the mushroom, broccoli and carrots , stir the add water cove and cook for 3 minutes.",
      "Add the boiled spaghetti pasta and the peanut sauce mix gently",
      "Garnish with sesame seed and serve.",
    ],
    cookTime: "30 minutes",
  },
  {
    id: "27",
    name: "Asian Style Peanut Noodles",
    ingredients: [
      "2 packs of dried rice noodles (approx. 260 g)",
      "3 tablespoon oil",
      "1 onion slices",
      "Half cup red peppers thinly sliced",
      "Half cup carrots thinly sliced",
      "Half cup broccoli florets",
      "Half cup cabbage shredded",
      "1 tablespoon ginger chopped",
      "Salt",
      "Half teaspoon black pepper crushed",
      "1 tablespoon peanut butter",
      "4 tablespoon water",
      "3 tablespoon light soy sauce",
      "Half cup spring onion chopped",
    ],
    instructions: [
      "In boiling water, add the dry noodles and cook for 2 minutes.",
      "Drain the water and set aside.",
      "In a wok or wide pan, heat oil and add the onions.",
      "Cook until the onions become translucent.",
      "Add the bell peppers, carrots, broccoli, cabbage and ginger then mix well.",
    ],
    cookTime: "15 minutes",
  },
  {
    id: "28",
    name: "Wimbi Porridge",
    ingredients: [
      "1 cup of grinded millet",
      "Water",
      "Half cup milk",
      "Sugar (optional)",
      "½ lemon (optional)",
      "Margarine (optional)",
    ],
    instructions: [
      "In a bowl, mix together the millet and 1 cup water.",
      "Heat 3 cups water in a pot and once it comes to a simmer, add the millet mixture, keep stirring.",
      "Once it comes to a boil, reduce the heat, cover the pot and let simmer for 15 minutes.",
      "Make sure to stir every few minutes so the porridge doesn't settle at the bottom.",
      "Add the lemon, milk and sugar and cook for 2 to 3 minutes.",
      "Serve with a teaspoon of margarine.",
    ],
    cookTime: "30 minutes",
  },
  {
    id: "29",
    name: "Creamy Bacon & Macaroni Salad",
    ingredients: [
      "2 cups macaroni pasta",
      "10 bacon slices",
      "1 cup cucumbers",
      "1 cup cherry tomatoes",
      "Mayonnaise",
      "1 tablespoon parsley",
      "1 tablespoon lemon juice",
      "1 teaspoon salt",
    ],
    instructions: [
      "Cook Pasta according to the package.",
      "Drain and set aside.",
      "Add oil to a pan, cook bacon slices for 4 minutes until crispy.",
      "Once done, remove from pan, place on kitchen to drain excess oil and chop into small chunks.",
      "In a large bowl add macaroni pasta, cucumber, cherry tomatoes, and the bacon",
      "In another bowl, mix mayonnaise, parsley, lemon juice and salt",
      "Add the Mayonnaise dressing to the large bowl and mix everything well. Serve and enjoy!",
    ],
    cookTime: "30 minutes",
  },
  {
    id: "30",
    name: "Rolex Recipe",
    ingredients: [
      "2 eggs",
      "1/4 cup chopped tomatoes",
      "1/4 cup chopped onions",
      "1/2 cup chopped cabbage",
      "Salt",
      "1/4 cup corriander leaves",
      "2 tablespoons margarine",
      "Cooked chapati",
    ],
    instructions: [
      "Crack 2 eggs into a bowl and mix them well.",
      "Add salt and black pepper.",
      "Add in chopped onions, chopped tomatoes, coriander, cabbage and mix well until it is will incorporated.",
      "You can also add any other spice or herb if you like.",
      "Heat up a pan, add in the margarine and spread it all over the pan and then pour the mixture into the pan.",
      "Let the omelette cook until it becomes firm.",
      "It should take roughly 2 minutes.",
      "Flip it over and then place the chapati on top.",
      "Take the chapati and omelette off the pan.",
      "Roll it up and serve",
    ],
    cookTime: "20 minutes",
  },
  {
    id: "31",
    name: "Breakfast Crepes",
    ingredients: [
      "3 eggs",
      "1 1/2 cups milk",
      "1/2 teaspoon vanilla essence",
      "1 cup all-purpose flour",
      "2 teaspoon sugar",
      "3 tablespoons margarine",
      "1 tablespoon melted peanut butter",
      "Sliced bananas",
    ],
    instructions: [
      "In a bowl, whisk together eggs, milk, vanilla, flour, sugar and melted margarine.",
      "Sieve the mixture.",
      "Grease a pan on medium heat with margarine and add 1/4 cup of the batter into the center of the pan and then swirl around.",
      "Cook for 45 seconds on each side and then fold it into half and then into quarters.",
      "Serve with a drizzle of peanut butter and bananas.",
    ],
    cookTime: "13 minutes",
  },
  {
    id: "32",
    name: "Spaghetti with Spicy Minced Meat",
    ingredients: [
      "400 grams tagliatelle or other pasta",
      "1 tablespoon margarine spread",
      "Cracked black pepper",
      "500 grams mixed minced meat",
      "1 large onion chopped small",
      "3 teaspoons garlic sliced",
      "3 teaspoons curry powder",
      "1 tablespoon tomato paste",
      "4 stock cubes",
      "1/2 cup frozen peas",
      "1/2 cup carrots diced small",
      "1/2 cup double cream",
      "Chopped coriander",
    ],
    instructions: [
      "For the minced meat, melt 1 tablespoon of margarine and cook the garlic and onion until soft and slightly browned.",
      "Add the curry powder and stir to cook for a few seconds then add the tomato paste, minced meat and carrots.",
      "Stir and allow for the meat to cook until the pink colour is finished while breaking the lumps being formed when cooking.",
      "Add the frozen peas and crumble 2 cooking cubes to act as seasoning.",
      "Add a little water if the meat dries off.",
      "Taste and adjust the seasoning by adding more cooking cubes if necessary, as well the cream to have a thick sauce.",
    ],
    cookTime: "45 minutes",
  },
  {
    id: "33",
    name: "Thai Fried Rice",
    ingredients: [
      "1 tablespoon margarine",
      "4 grams onions chopped",
      "200 grams rice (cooked)",
      "2 tablespoons raisins",
      "3 tablespoons tomato ketchup",
      "1 teaspoon sugar",
      "1 teaspoon light soy sauce",
      "1 teaspoon fish sauce",
      "2 pieces eggs",
      "2 pieces fried chicken drumsticks",
      "2 pieces meat free Sausage",
      "2 tablespoons margarine",
    ],
    instructions: [
      "Cut sausages into half.",
      "Slice ends into quarters and quickly fry in a pan with melted margarine, set aside.",
      "Fry sunny side up eggs on a pan heated with margarine, set aside.",
      "In a small bowl, mix together Ketchup, light soy sauce, fish sauce, and sugar. ",
      "Melt margarine in a pan, add in onions then sauté over medium heat. ",
      "Add raisins followed by cooked rice, stir fry until rice softens.",
      "Pour mixture into the pan and then continue stirring to coat the rice.",
      "Season with salt and pepper as needed.",
      "Remove from heat and set aside.",
      "To assemble, mold the fried rice using a small bowl then tip it over a plate.",
      "Gently place the fried eggs over the rice.",
      "Arrange the sausages and fried chicken around the rice.",
      "Add sliced tomatoes and lettuce on the side (optional).",
      "Serve and enjoy!",
    ],
    cookTime: "40 minutes",
  },
  {
    id: "34",
    name: "Beef Stir Fry Noodles",
    ingredients: [
      "2 Packet Noodles",
      "beef strips",
      "2 tablespoons margarine",
      "1/2 Green Bell Pepper, Sliced",
      "2-3 Sprig of Spring Onion",
      "1 tablespoon garlic, minced",
      "1 small onion, chopped",
      "1 tablespoon corn flour",
      "1 chicken stock cube",
      "1/2 teaspoon garlic powder",
      "5 tablespoon soy sauce",
      "3 tablespoons oyster sauce",
      "3 tablespoons chicken stock",
      "1 tablespoon brown sugar",
      "1 teaspoon sesame oil",
    ],
    instructions: [
      "Marinate the beef strips with garlic powder, stock and corn Flour.",
      "Mix and leave to marinate for at least an hour.",
      "Mix the soy sauce, oyster sauce, chicken stock and sesame oil and set aside.",
      "Add margarine to a pan and let melt.",
      "Add the marinated beef and fry until brown on all sides.",
      "Transfer to a bowl and set aside.",
      "Place the same pan on the heat and add the chopped onions and garlic and saute until fragrant.",
      "Add the chopped peppers and cook for a minute.",
      "Add the spring onions and cooked beef back into the pan.",
      "Pour the prepared sauce in the pan and let cook for another minute.",
      "Add boiled noodles to the pan and mix well.",
      "Serve with a garnish of spring onions.",
    ],
    cookTime: "35 minutes",
  },
  {
    id: "35",
    name: "Waffles",
    ingredients: [
      "40 grams margarine",
      "1 cup plain flour",
      "1/2 teaspoon salt",
      "2 teaspoons baking powder",
      "1 tablespoon white sugar",
      "1 large egg",
      "3/4 cup warm milk",
      "1/2 teaspoon vanilla extract",
    ],
    instructions: [
      "In a medium bowl, whisk together melted margarine, egg, milk, vanilla and sugar until well mixed.",
      "Sift in flour, baking powder, and salt and stir until smooth batter is formed.",
      "Ladle waffle batter into preheated Waffle iron and cook until golden and crispy.",
      "Serve warm with maple syrup and fresh fruits.",
    ],
    cookTime: "50 minutes",
  },
  {
    id: "35",
    name: "Chicken Frittata",
    ingredients: [
      "2 - 3 ripe plantains",
      "7 eggs",
      "1/2 cup chopped onions",
      "3 cloves minced garlic",
      "1 large tomato chopped",
      "1 cup green bell pepper chopped",
      "3 tablespoons margarine",
      "1 chicken breast",
      "Salt",
      "1/2 teaspoon boullion powder",
      "1/4 teaspoon ground black pepper",
      "Vegetable oil for deep frying",
    ],
    instructions: [
      "Peel the plantains then cut 1/4 inch slices.",
      "Place oil in a pan up to 2-3 inches and heat.",
      "Gently place the plantain slices into the pan one at a time then fry one side for about 2 minutes.",
      "Flip to the other sides and cook for about 2 minutes.",
      "Remove and place on a paper towel to absorb excess oil.",
      "Place 1 tablespoon margarine in a pan.",
      "Season with salt and pepper and let it cook for 3 minutes on each side.",
      "Once cooked, chop into small pieces.",
      "Place 2 tablespoons of margarine in a skillet and heat up on medium heat.",
      "Add onions and garlic and sauté until fragrant.",
      "Add the chopped tomatoes and cook for about 2 minutes.",
      "Then add the chopped chicken and stir for about 2 minutes.",
      "Add the bell pepper, salt and black pepper and stir for about 2 minutes.",
      "Turn off the heat.",
      "In a large bowl, crack in all the 3 eggs add the bouillon powder and whisk to combine.",
      "Add the chicken-bell pepper mixture into the egg and mix.",
      "Preheat oven to180 degrees Celcius.",
      "Rub a pie plate with about a teaspoon of margarine.",
      "Pour the mixture into the pie plate.",
      "Arrange the fried plantains on top of the egg mixture.",
      "Place the pie plate in the preheated oven and bake for 35 minutes.",
      "Now remove and check to make sure the egg is set in the middle.",
      "If it is set take it out. If it isn't set, place it back in the oven and turn off the heat.",
      "Let it stay in the oven for about 5-10 minutes then take it out.",
      "Garnish with chopped parsley if desired then cut into triangles and serve warm.",
    ],
    cookTime: "1 hour 5 minutes",
  },
  {
    id: "36",
    name: "Oat and Banana Porridge",
    ingredients: [
      "Rolled oats",
      "Ripe bananas",
      "Almond milk",
      "Cinnamon",
      "Honey (optional)",
    ],
    instructions: [
      "In a medium saucepan, heat 1 1/2 cups of almond milk over medium heat until it starts to simmer.",
      "Stir in 1 cup of rolled oats and continue to cook, stirring frequently, until the mixture thickens, about 5 minutes.",
      "Peel and mash 2 ripe bananas and add them to the saucepan, stirring until they are fully incorporated.",
      "Stir in 1 teaspoon of cinnamon and a drizzle of honey (optional) to taste.",
      "Cook for an additional 2 minutes, stirring occasionally, until the porridge is heated through.",
      "Serve hot, garnished with additional cinnamon or sliced bananas if desired.",
    ],
    cookTime: "15 minutes",
  },
  {
    id: "37",
    name: "Chakalaka",
    ingredients: [
      "White and red onion",
      "Tomatoes",
      "Mixed herbs (ginger, garlic, fresh thyme, cilantro and parsley)",
      "Green or red chilli pepper",
      "Veggies (green beans, carrots, red and green bell peppers).",
      "Cannellini beans or baked beans",
      "Paprika, curry powder and cayenne (optional).",
      "Bouillon powder or paste",
      "Salt and pepper",
    ],
    instructions: [
      "Chop onions and finely chop ginger, garlic and green chilies (removing the seeds).",
      "Heat oil in a pan over medium high heat.",
      "Once hot, add you chopped onions.",
      "Sauté, stirring occasionally, until the onion softens and becomes translucent.",
      "Add ginger, garlic and chiles and stir.",
      "Chop bell peppers, cut green beans and carrots.",
      "(for a shortcut, you can grate the carrots) Add these veggies to the pan and give it a nice stir.",
      "Add the curry powder, paprika and cayenne and stir along with salt, black pepper and fresh thyme.",
      "Stir in chopped tomatoes and combine well.",
      "Add bouillon powder or paste.",
      "Reduce heat to medium and simmer till veggies are cooked, about 8-10 minutes.",
      "Then add the baked beans and stir.",
      "Simmer for 2 -3 more minutes to heat up the beans.",
      "Garnish with some more fresh herbs like cilantro, parsley or thyme.",
      "Serve with pap, barbecued meats and seafood, boiled basmati rice and baked meat.",
    ],
    cookTime: "45 minutes",
  },
  {
    id: "38",
    name: "Jamaican Green Banana Porridge",
    ingredients: [
      "4 green bananas",
      "1 cup coconut milk",
      "1 cup unsweetened almond milk or any milk of your choice",
      "Water",
      "1/2 cup sweetened condensed milk",
      "1 teaspoon vanilla extract",
      "1/2 teaspoon ground cinnamon",
      "1/2 teaspoon ground nutmeg",
      "1/4 teaspoon ground allspice",
      "1/2 teaspoon Kosher salt",
    ],
    instructions: [
      "Peel and cut the green banana.",
      "Once peeled, add green banana, coconut milk, and almond milk to a blender.",
      "Blend on medium speed until the mixture is smooth.",
      "Add mixture from blender to boiling water and stir until the banana mixture is dissolved in the water. ",
      "Reduce heat and continue to cook on medium heat, stirring occasionally, for about 12 minutes, until the porridge thickens.",
      "After 12 minutes, stir in vanilla extract, allspice, cinnamon, and nutmeg, and allow to cook for an additional 2 minutes.",
      "Remove from heat and stir in condensed milk to taste.",
      "Serve and enjoy!",
    ],
    cookTime: "25 minutes",
  },
  {
    id: "39",
    name: "",
    ingredients: ["eggs", "tomatoes", "", "", "", "", "", "", "", ""],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "40",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "41",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "42",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "43",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "44",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "45",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "46",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "47",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "48",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "49",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "50",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "51",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "52",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "53",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "54",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
  {
    id: "55",
    name: "",
    ingredients: ["eggs", "tomatoes"],
    instructions: [""],
    cookTime: "",
  },
];
